Rate-Restaurants-App/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rate_Restaurants_App.Data;
using Rate_Restaurants_App.Models;
using Rate_Restaurants_App.ViewModels;

namespace Rate_Restaurants_App.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RestaurantController(ApplicationDbContext context)
        {
            _context = context;

        }

        // GET: Restaurant
        public async Task<IActionResult> Index(int? TagId)
        {
            ViewBag.TagId = new SelectList(_context.Tag.OrderBy(c => c.Name).ToList(), "Id", "Name");
            if (_context.Restaurant == null)  return Problem("Entity set 'ApplicationDbContext.Restaurant'  is null.");
            var restaurant = await _context.Restaurant.Include(p => p.Tags).ToListAsync();
            if (TagId.HasValue)
            {
                restaurant = restaurant.Where(p => p.Tags.Any(c => c.Id == TagId)).ToList();
            }

            return View(restaurant);
        }

        // GET: Restaurant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant.Include(p => p.Tags).SingleAsync(i => i.RestaurantId == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            restaurant.Reviews = await _context.Review.Where(x => x.RestaurantId == restaurant.RestaurantId)
                .Include(e => e.Restaurant).ToListAsync();


            foreach (var review in restaurant.Reviews)
            {
                review.Author = _context.Users.Find(review.AuthorId);
            }

            return View(restaurant);
        }

        // GET: Restaurant/Create
        [Authorize]
        public IActionResult Create()
        {
            List<SelectListItem> selectListItems = _context.Tag.Select(a => new SelectListItem
            {
                Text = a.Name,
                Value = a.Id.ToString()
            }).ToList();
            var restaurant = new Restaurant();
            PopulateSelectedTagData(restaurant);
            return View(restaurant);
        }

        // POST: Restaurant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("RestaurantId,Name, selectedTags")] Restaurant restaurant, string[] selectedTags)
        {
            if (ModelState.IsValid)
            {
                restaurant.Reviews = new List<Review>();
                UpdateRestaurantTags(selectedTags, restaurant);
                _context.Add(restaurant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(restaurant);
        }

        // GET: Restaurant/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }


            var restaurant = _context.Restaurant.Include(p => p.Tags)
                .Single(i => i.RestaurantId == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            /*
            var allTagsList = _context.Tag.ToList();
            restaurantTagViewModel.AllTags = allTagsList;
            */
            PopulateSelectedTagData(restaurant);
            return View(restaurant);
        }

        // POST: Restaurant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id,
            [Bind("RestaurantId, Name, selectedTags")] Restaurant restaurant, string[] selectedTags)
        {
            var restaurantToUpdate = _context.Restaurant.Include(p => p.Tags)
                .Single(i => i.RestaurantId == id);
            restaurantToUpdate.Name = restaurant.Name;
            if (id != restaurantToUpdate.RestaurantId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    
                    //restaurant.Tags = new HashSet<Tag>(restaurant.Tags.Select(b => b.Id));
                    UpdateRestaurantTags(selectedTags, restaurantToUpdate);
                    _context.Update(restaurantToUpdate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RestaurantExists(restaurantToUpdate.RestaurantId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            return View();
        }

        private void UpdateRestaurantTags(string[] selectedTags, Restaurant restaurant)
        {
            if (selectedTags == null)
            {
                restaurant.Tags = new List<Tag>();
                return;
            }

            var selectedTagsHS = new HashSet<string>(selectedTags);
            var restaurantTags = new HashSet<int>(restaurant.Tags.Select(b => b.Id));

            foreach (var tag in _context.Tag)
            {
                if (selectedTagsHS.Contains(tag.Id.ToString()))
                {
                    if (!restaurantTags.Contains(tag.Id))
                    {
                        restaurant.Tags.Add(tag);
                    }
                }
                else
                {
                    if (restaurantTags.Contains(tag.Id))
                    {
                        restaurant.Tags.Remove(tag);
                    }
                }
            }
        }

        // GET: Restaurant/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Restaurant == null)
            {
                return NotFound();
            }

            var restaurant = await _context.Restaurant
                .FirstOrDefaultAsync(m => m.RestaurantId == id);
            if (restaurant == null)
            {
                return NotFound();
            }

            return View(restaurant);
        }

        // POST: Restaurant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Restaurant == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Restaurant'  is null.");
            }

            var restaurant = await _context.Restaurant.FindAsync(id);
            if (restaurant != null)
            {
                _context.Restaurant.Remove(restaurant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RestaurantExists(int id)
        {
            return (_context.Restaurant?.Any(e => e.RestaurantId == id)).GetValueOrDefault();
        }


        public IActionResult AddReview()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurant, "RestaurantId", "Name");

            return View(new Review());
        }


        // POST: Restaurant/AddReview/5
        [HttpPost, ActionName("AddReview")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> AddReview(int id, Review review)
        {
            /*
                       if (_context.Restaurant == null)
                       {
                           return Problem("Entity set 'ApplicationDbContext.Restaurant'  is null.");
                       }
                       var restaurant = await _context.Restaurant.FindAsync(id);
                       if (restaurant != null)
                       {
                           _context.Restaurant.Remove(restaurant);
                       }
                       
                       await _context.SaveChangesAsync();
                       return RedirectToAction(nameof(Index)); */
            if (_context.Restaurant == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Restaurant'  is null.");
            }

            var restaurant = await _context.Restaurant.FindAsync(id);
            var userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
            if (userId == null) return RedirectToAction(nameof(Index));
            review.Restaurant = restaurant;
            review.RestaurantId = restaurant.RestaurantId;
            review.Author = _context.Users.Find(userId);
            review.AuthorId = userId;

            _context.Add(review);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", review.AuthorId);

Rate-Restaurants-App/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Rate_Restaurants_App.Data;
using Rate_Restaurants_App.Models;

namespace Rate_Restaurants_App.Controllers
{
    public class ReviewController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReviewController(ApplicationDbContext context)
        {
            _context = context;
            
        }

        // GET: Review
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Review.Include(r => r.Author).Include(r => r.Restaurant);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Review/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Author)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

           // review.Author = _context.Users.Find(review.AuthorId);
            return View(review);
        }
        /*
        // GET: Review/Create
        public IActionResult Create()
        {
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["RestaurantId"] = new SelectList(_context.Restaurant, "RestaurantId", "Name");
            
            return View(new Review());
        }

        // POST: Review/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReviewId,Rating,Text,RestaurantId,AuthorId")] Review review)
        {
            review.Restaurant = _context.Restaurant.Find(review.RestaurantId);
            review.Author = _context.Users.Find(review.AuthorId);
            if (ModelState.IsValid)
            {
                review.Restaurant.Reviews.Add(review);
                review.Author.Reviews.Add(review);
                _context.Add(review);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", review.AuthorId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurant, "RestaurantId", "Name", review.RestaurantId);
            return View(review);
        }               */

        // GET: Review/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review.FindAsync(id);
            if (review == null)
            {
                return NotFound();
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", review.AuthorId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurant, "RestaurantId", "Name", review.RestaurantId);
            return View(review);
        }

        // POST: Review/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("ReviewId,Rating,Text,RestaurantId,AuthorId")] Review review)
        {
            if (id != review.ReviewId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(review);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReviewExists(review.ReviewId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AuthorId"] = new SelectList(_context.Users, "Id", "Id", review.AuthorId);
            ViewData["RestaurantId"] = new SelectList(_context.Restaurant, "RestaurantId", "Name", review.RestaurantId);
            return View(review);
        }

        // GET: Review/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Review == null)
            {
                return NotFound();
            }

            var review = await _context.Review
                .Include(r => r.Author)
                .Include(r => r.Restaurant)
                .FirstOrDefaultAsync(m => m.ReviewId == id);
            if (review == null)
            {
                return NotFound();
            }

            return View(review);
        }

        // POST: Review/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Review == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Review'  is null.");
            }
            var review = await _context.Review.FindAsync(id);
            if (review != null)
            {
                _context.Review.Remove(review);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReviewExists(int id)
        {
          return (_context.Review?.Any(e => e.ReviewId == id)).GetValueOrDefault();
        }
    }
}

Rate-Restaurants-App/Views/Review/Create.cshtml
@model Rate_Restaurants_App.Models.Review

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class ="form-control" asp-items="ViewBag.RestaurantId"></select>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="ViewBag.AuthorId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rate-Restaurants-App/Views/Review/Delete.cshtml
@model Rate_Restaurants_App.Models.Review

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Review</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Restaurant.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ReviewId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Rate-Restaurants-App/Views/Review/Details.cshtml
@model Rate_Restaurants_App.Models.Review

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Restaurant)
        </dt>
        <dd class="col-sm-10">
            <p>
                <a asp-controller="Restaurant" asp-action="Details" asp-route-id="@Model.RestaurantId">
                    @Html.DisplayFor(model => model.Restaurant!.Name)
                </a>
            </p>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author!.UserName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ReviewId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Rate-Restaurants-App/Views/Review/Edit.cshtml
@model Rate_Restaurants_App.Models.Review

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Review</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ReviewId" />
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RestaurantId" class="control-label"></label>
                <select asp-for="RestaurantId" class="form-control" asp-items="ViewBag.RestaurantId"></select>
                <span asp-validation-for="RestaurantId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.AuthorId"></select>
                <span asp-validation-for="AuthorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Rate-Restaurants-App/Views/Review/Index.cshtml
@model IEnumerable<Rate_Restaurants_App.Models.Review>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Text)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Author)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant!.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author!.UserName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ReviewId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ReviewId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ReviewId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>